# Generated by Django 5.1.5 on 2026-05-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_hls_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_playlist',
        ),
    ]
