# Generated by Django 5.1.5 on 2026-05-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_hls_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
